### ISSUE TITLE
Update `repository` value in Cargo.toml of parachain pallets

### ISSUE THREAD

**Issue by siman** [dappforce/subsocial-parachain#148]
Now it is like this:
```
repository = 'https://github.com/dappforce/dappforce-subsocial-node'
```

Should be like this:
```
repository = 'https://github.com/dappforce/subsocial-parachain'
```

See old migrated pallets such as: posts, spaces, etc.

**Comment by bolajahmad** [comment]
I would like to fix this, does this happen in only the para chain pallets or do we need to update it on all pallets? I can work on this if no one is on it yet.

**Comment by siman** [comment]
I think updating it in just parachain pallets is enough

**Comment by bolajahmad** [comment]
Hi Alex,

Thank you for replying, I have fixed the issue and opened a pull request on it. I had trouble adding reviewers and the expected labels, I was hoping I could have more guide on it or if that’s all. 

Thank you for also opening the issue
