### ISSUE TITLE
Prepare functions for migration

### ISSUE THREAD

**Issue by olehmell** [dappforce/subsocial-parachain#90]
## What to do?

Write `sudo` extrinsics to migrate all the data from solochain to parachain.

## Progress

- [x] Spaces and Space follows: #119

#124:
- [x] Roles
- [x] Posts
- [x] Reactions
- [x] Profiles
- [x] Account follows

**Comment by F3Joule** [comment]
Blocked for now on reviewing all of the #88

**Comment by olehmell** [comment]
Give me branch for testing @F3Joule
